# Mounting sensitive file system paths can lead to information disclosure and compromise of the host systems
    # Kubernetes Documentation - Volumes
    # MITRE, CWE-668 - Exposure of Resource to Wrong Sphere

---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /data
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /etc # Sensitive
